allowBuilds:
  '@bitdisaster/exe-icon-extractor': true
  '@nestjs/core': true
  '@sentry/cli': true
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  keytar: true
  macos-alias: true
  protobufjs: true
  sharp: true
  fs-xattr: true
  appdmg: true
